version: '2.2'

services:
    kernel_debug:
        build: ./
        container_name: kernel_debug
        volumes: 
            - ./exp:/root/exp
            - ./corescripts:/root/corescripts
            - ./pwn:/root/pwn
            - ./gdb_internal.sh:/gdb_internal.sh
            - ./.gdbinit:/root/.gdbinit
        environment:
            - LC_CTYPE=C.UTF-8
            - WORKDIR=/root/pwn
        network_mode: host
        privileged: true
        restart: unless-stopped
        
